version: '3.8'

services:
  app:
    image: eclipse-temurin:23-jdk
    container_name: springboot_app
    ports:
      - "8080:8080"
    volumes:
      - ./out/artifacts/demo_jar/demo.jar:/demo.jar
    depends_on:
      - mysql
    command: ["java", "-jar", "/demo.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fitness_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: default
      SPRING_MAIN_WEB-APPLICATION-TYPE: servlet  # Specify the web application type

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fitness_db
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s

volumes:
  mysql_data:
